DROP DATABASE IF EXISTS turtle_db;
CREATE DATABASE turtle_db;

USE turtle_db;

CREATE TABLE island (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(30)
);

CREATE TABLE usa (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  island_id INT NULL,
  FOREIGN KEY (island_id)
  REFERENCES island(id)
  ON DELETE SET NULL
);